//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfdelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrder
    {
        public int DeliverOrderId { get; set; }
        public System.DateTime DeliverOrderDate { get; set; }
        public int DeliverQty { get; set; }
        public int TotalInv { get; set; }
        public int TotalBox { get; set; }
        public int TotalBundle { get; set; }
        public int TotalSack { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string StaffName { get; set; }
        public int SalesOrderId { get; set; }
        public int DeliverPlaceId { get; set; }
    
        public virtual DeliverPlace DeliverPlace { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
