//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfdelivery
{
    using System;
    
    public enum StaffPosition : int
    {
        Driver = 0,
        Worker = 1
    }
}
